#!/bin/bash

# Transform all the .pic files generated by the deploymentSequenceDiagram analysis into many .pdf

highest_num=$(ls deploymentSequenceDiagram-*.pic | grep -o '[0-9]\+' | sort -nr | head -n1)

# Process all the .pic files
for i in $(seq 1 $highest_num);
do 
    pic2plot -T ps deploymentSequenceDiagram-$i.pic > output-$i.ps
    ps2pdf output-$i.ps output-$i.pdf
done  
